<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8tjvns\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8tjvns/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY8tjvns.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY8tjvns\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY8tjvns\appProdProjectContainer([
    'container.build_hash' => 'Y8tjvns',
    'container.build_id' => '63577f16',
    'container.build_time' => 1618889364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8tjvns');
