<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmwvlhe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmwvlhe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXmwvlhe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXmwvlhe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXmwvlhe\appDevDebugProjectContainer([
    'container.build_hash' => 'Xmwvlhe',
    'container.build_id' => 'f93188cf',
    'container.build_time' => 1618888419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmwvlhe');
